# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
      - image: redis
      - image: arungupta/couchbase-server
      - image: aerospike/aerospike-server
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci-go-test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/rom8726/circleci-go-test
    steps:
      - checkout

      - setup_remote_docker
      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   CircleCI-Public/circleci-demo-docker:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push CircleCI-Public/circleci-demo-docker:$TAG

      # specify any bash command here prefixed with `run: `
      - run: go get github.com/constabulary/gb/...
      - run: go get -u github.com/golang/lint/golint
#      - run: go get -u github.com/alecthomas/gometalinter
#      - run: gometalinter --install
      - run: gb vendor restore
      - run: gb build
      - run: sh couchbase_setup.sh
      - run: AEROSPIKE_HOST=$(sudo docker inspect -f '{{.NetworkSettings.IPAddress }}' aerospike)
      #- run: go get -v -t -d ./...
      - run: GOPATH=$GOPATH:$PWD:$PWD/vendor; go test -v ./src/...
